thebergamo/react-native-fbsdk-next

README.md

docs: update the title from analytics to app events (#14)

---

.github/workflows/ci.yml
ios/RCTFBSDK/core/RCTFBSDKAppEvents.m
react-native-fbsdk-next.podspec

feat(ios, sdk): upgrade to FBSDK version 9.3.x

---

README.md

Updates the README.md with correct manually link instructions for iOS.
Test Plan:

docs(README): correct iOS manual link instructions

---

package.json
react-native-fbsdk-next.podspec

This is apparently needed for Xcode 12 compatibility
Reference: facebook/react-native#29633

fix: update React-Core pod

---

README.md

This is not entirely obvious for non native developers.

docs: mention the required imports AppDelegate.m

---

README.md

Included extended troublshooting information regarding the 'Undefined symbols for architecture x86_64' error in response to issue #43.
Test Plan:

Update README.md to include troubleshooting for 'Undefined symbols for architecture x86_64' error

---

RNFBSDKExample/android/app/src/main/AndroidManifest.xml

docs(example): fix AndroidManifest.xml typo

---

RNFBSDKExample/App.js
RNFBSDKExample/__tests__/App-test.js
src/FBLoginButton.js

Test Plan:
The commit itself adds a test to demonstrate a usecase.

chore(test): add testID optional type to login button for use in testing

---

types/FBLoginButton.d.ts

Adds `testID` to the typescript type information.
Test Plan:
Testing the module in a production app compiled with tsc.

fix(type): add new testID to typescript definition file

---

README.md
android/src/main/java/com/facebook/reactnative/androidsdk/FBSettingsModule.java
ios/RCTFBSDK/core/RCTFBSDKSettings.m
src/FBSettings.js
types/FBSettings.d.ts

Adding wrapper for setAppID to RN library

feat: Add setAppID

---

README.md

This PR was suggested at the end of https://github.com/thebergamo/react-native-fbsdk-next/issues/66. I really appreciate the work you all put into this. I'll be looking for more opportunities to contribute in the future.

docs(README): Add section about getting events to show up in the Facebook Events Manager

---

RNFBSDKExample/ios/Podfile.lock
RNFBSDKExample/ios/RNFBSDKExample.xcodeproj/project.pbxproj
RNFBSDKExample/package.json
RNFBSDKExample/yarn.lock
package.json
react-native-fbsdk-next.podspec

Update to latest underlying SDK - refresh example in the process of local testing
https://github.com/facebook/facebook-ios-sdk/blob/main/CHANGELOG.md#1221

feat(ios, sdk): facebook-ios-sdk from 12.1.0 to 12.2.1

---

src/index.ts

Don't want anyone having type trouble using this package, simply export all types we have declared as export from all files.

feat: Export all types

---

README.md

docs: Update IOS installation instructions

---

README.md

@mikehardy As I mentioned on the open Github issue I would like to provide some clarification about the auto app install to avoid some future misunderstandings.

docs(README): clarify auto App Installs in Expo

---

src/FBAppEventsLogger.ts

Upstream fix was released in android sdk 13.1.0
https://github.com/facebook/facebook-android-sdk/issues/1047

Remove setUserID(null) android workaround

---

README.md

Update docs related to the [last fix](https://github.com/thebergamo/react-native-fbsdk-next/pull/320)

docs(ios): Update docs related to the last fix

---

README.md

docs(android): add tip about Key Hash generation

---

README.md

update report codes

---

README.md

update docs with the latest import needed

docs: Change import FBSDKCoreKit.h to FBSDKCoreKit-swift.h

---

CONTRIBUTING.md
README.md

Updates the **Troubleshooting** section with the info from #488, the Limited Login for iOS info from #514, and makes some minor miscellaneous formatting tweaks for consistency.
Thanks for looking!

docs: Update README.md with more troubleshooting info

---

RNFBSDKExample/ios/Podfile.lock
RNFBSDKExample/ios/RNFBSDKExample.xcodeproj/project.pbxproj
react-native-fbsdk-next.podspec

simple bump to 17.4.0 for iOS SDK
Fixes #574 (at least for iOS)

fix(ios, sdk): adopt facebook-ios-sdk 17.4.0
