thebergamo/react-native-fbsdk-next

- README.md
- android/src/main/java/com/facebook/reactnative/androidsdk/FBSettingsModule.java
- example/index.js
- ios/RCTFBSDK/core/RCTFBSDKSettings.m
- src/FBSettings.js
From issue facebook/react-native-fbsdk#840
I wrap the initialize function from native, the original pr is facebook/react-native-fbsdk#841
> feat: wrap initialize sdk function

- android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java
`AccessToken` requires only `accessToken`, `applicationId` and `userId`. See: https://github.com/facebook/facebook-android-sdk/blob/master/facebook-core/src/main/java/com/facebook/AccessToken.java#L111-L121. Other fields are nullable.
Fixes https://github.com/facebookarchive/react-native-fbsdk/issues/456.
> fix: Support AccessToken nullable fields

- README.md
The old link is broken. This updates to the correct link. We might change the step numbers because step 3 isn't reflected in the guide for some reason.
> docs(README): update link to upstream iOS Getting Started Guide

- android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java
- android/src/main/java/com/facebook/reactnative/androidsdk/FBSDKPackage.java
Propose to fix a build error in android. Missing constructor on FacebookProfile.
thebergamo#30
Test Plan:
In a project with react-native-fbsdk-next as dependency enter in android folder and run:
cd android && ./gradlew app:installDebug -PreactNativeDevServerPort=8081
> fix: compileDebugJavaWithJavac

- android/build.gradle
Setting buildToolsVersion is no longer recommended, it'll default to Android Gradle Plugin defaults. It makes DX worse by requiring multiple versions of build tools by various dependencies require various versions.
> build(android): remove build tools version

- README.md
After work on #30, older versions are functional again but without testing they may break again in the future. Expose this tradeoff to library consumers
> docs(README): note that RN0.60+ actually works, but is not supported

- android/src/main/java/com/facebook/reactnative/androidsdk/FBAccessTokenModule.java
These are needed to avoid console warnings about NativeEventEmitter being
created without the required native module implementations
Test Plan:
It's impossible for these methods to have bugs because they're just stubs ;-)
I've integrated it locally via patch-package, and it's the same change I've successfully made + released in react-native-firebase and react-native-device-info, as well as patched locally in netinfo (PR there is merged but not released yet).
> fix(android, event-emitter): add required event listener stubs for react-native 0.65

- android/src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java
- ios/RCTFBSDK/core/RCTFBSDKAppEvents.m
- src/FBAppEventsLogger.js
- src/util/validate.js
- types/FBAppEventsLogger.d.ts
This function has been on both android & ios native SDKs for a couple of years now... just exposing it to RN land
**Test plan**
used this branch on our app and logged some events, validated they show up on Facebook's Events Manager debugger view:
iOS
<p align="center">
</p>
Android
<p align="center">
</p>
> feat: add logProductItem

- ios/RCTFBSDK/core/RCTFBSDKSettings.m
fix Xcode build warnings: `'NSStringArray' is deprecated: Use NSArray<NSString *>`
sync types with [facebook-ios-sdk](https://github.com/facebook/facebook-ios-sdk/blob/main/FBSDKCoreKit/FBSDKCoreKit/FBSDKSettings.m#L433)
> fix: NSStringArray warnings

- README.md
Hey guys!
I've recently ran into an issue when switching from the old discontinued `react-native-fbsdk` package to this one. Fortunately, my problem was solved with an instruction on the comments of one of the issues here ([this one](https://github.com/thebergamo/react-native-fbsdk-next/issues/96#issuecomment-922409601)), so I thought I'd add this to the readme, seemed useful!
_P.S.: I could not find any guidelines regarding PRs to this repo, so I hope this simple one is ok 😅_
> docs(README): update troubleshooting session in readme to include fix to 'AppId not found'

- ios/RCTFBSDK/core/RCTFBSDKAppEvents.m
- ios/RCTFBSDK/core/RCTFBSDKSettings.m
- react-native-fbsdk-next.podspec
- src/FBAppEventsLogger.js
This PR upgrades [Facebook SDK for iOS](https://github.com/facebook/facebook-ios-sdk) to 11.2.1.
Method `updateUserProperties` of the `RCTFBSDKAppEvents` class was removed in release 11.0.0 ([changelog](https://github.com/facebook/facebook-ios-sdk/blob/main/CHANGELOG.md#1100)).
Test Plan:
My app mostly logs events so I tested that it compiles, launches and events are visible in the "Test Events" tab in the Facebook Events Manager.
> feat(ios): Upgrade to Facebook iOS SDK 11.2.1

- .github/workflows/ci.yml
This is a test-only change intended to accelerate the CI time to completion for the iOS build
I grabbed it from react-native-firebase where it is used and has been quite effective for us for a long time, should help here in combination with this part of the example script Podfile edits, which are in place to allow compiler caches to work:
https://github.com/thebergamo/react-native-fbsdk-next/blob/63a6230e2f7f7b1544ab748f29a0aa09441bf43b/refresh-example.sh#L49-L53
https://github.com/thebergamo/react-native-fbsdk-next/blob/63a6230e2f7f7b1544ab748f29a0aa09441bf43b/RNFBSDKExample/ios/Podfile#L29-L36
> test(ci): use ccache / pod cache to accelerate iOS builds

- README.md
- RNFBSDKExample/ios/Podfile.lock
- RNFBSDKExample/ios/RNFBSDKExample.xcodeproj/project.pbxproj
- ios/RCTFBSDK/core/RCTFBSDKAccessToken.m
- ios/RCTFBSDK/core/RCTFBSDKAppEvents.m
- ios/RCTFBSDK/core/RCTFBSDKGraphRequestConnectionContainer.m
- ios/RCTFBSDK/core/RCTFBSDKGraphRequestManager.m
- ios/RCTFBSDK/core/RCTFBSDKSettings.m
- ios/RCTFBSDK/share/RCTFBSDKShareDialog.m
- react-native-fbsdk-next.podspec
- refresh-example.sh
Upgrade FBSDK to v12.1.0.  This fixes #55.
**BREAKING CHANGE:**
* For iOS, `getAdvertiserID` will always return null, as the upstream FBSDK no longer provides the advertiserID
* iOS minimum deployment target changes from 9 to 10, due to upstream FBSDK change
* `setAdvertiserTrackingEnabled` always returns `true` now, as it will never fail; no function change from previous implementation
Here is a summary of the changes:
* Updated `react-native-fbsdk-next.podspec` to specify FBSCK v12.1.0
* Fixed compiler warnings and deprecations for iOS builds
* Updated README to add additional instructions for running the example
* Updated `refresh-example.sh` to extract the Facebook App ID into a variable
* Updated example folder artifacts based on latest changes
I tested these changes by running the …
> feat(ios)!: upgrade facebook-ios-sdk to v12

- README.md
The iOS native initialization style has changed with the update to facebook-ios-sdk v11 contained in v5 here, and it the docs are out of date
How to do it now https://github.com/thebergamo/react-native-fbsdk-next/pull/125/files#diff-be03dd17b2019e2f4ddd389c2a9dbfceaf560485d2111c8462bc0c8530695878
> [FBSDKApplicationDelegate.sharedInstance initializeSDK];
I will also update the release notes
Fixes #131
> docs(README, v5): update ios native initialization to match new style

- jest/mocks/index.js
Hello! After this [merge](https://github.com/thebergamo/react-native-fbsdk-next/pull/140) I tried to update the lib and use the mocks but I'm getting the following error:
So I change the import to the component itself like react-native-permission [does](https://github.com/zoontek/react-native-permissions/blob/master/mock.js) and started working on the app.
Also, I'm adding the `/* eslint-env jest */` to avoid eslint error on this file (didn't see this on the first PR)
> fix: adjust import and jest eslint env

- ios/RCTFBSDK/core/RCTFBSDKAppEvents.m
According to #159, there're some deprecated methods still in use,
luckily on iOS, we'll only have to change `FBSDKAppEvents` to `FBSDKAppEvents.shared`,
still having trouble developing android, which will take me a while, so this pr is only going to fix iOS
> fix(iOS)!: update deprecated methods

- README.md
- ios/RCTFBSDK.xcodeproj/project.pbxproj
- ios/RCTFBSDK/core/RCTFBSDKAEMReporter.m
- src/FBAEMReporter.ts
- src/index.ts
close #153
[Aggregated Event Measurement for Facebook App Events](https://developers.facebook.com/docs/app-events/guides/aggregated-event-measurement/)
1. fix project file issue in `project.pbxproj` (not a serious issue, it's just cannot open some files with xcode when developing this project)
2. create `FBAEMReporter.logAEMEvent` method
3. add a section for AEM in README.md
a. The official document told us to `Add the following to your Podfile: pod 'FBAEMKit'`, but in our case, `FBAEMKit` is already a dependency for `FBSDKCoreKit`, so I didn't mention it in README.md
> feat(ios): AEM logger

- android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginButtonManager.java
- android/src/main/java/com/facebook/reactnative/androidsdk/RCTLoginButton.java
Resolved some warnings in RCTLoginButton and FBLoginButtonManager
* nullable warnings
* variable should be marked as `final` warning
* variable never accessed warning
1. `yarn example:install && yarn example:devcopy && yarn example:install && yarn example:android`
2. Press on the login button
3. The alert should show after the login process, it means the onChange is working properly, no matter login is successful or not, I tested `onCancel` and `onError`.
> refactor: resolve warnings in RCTLoginButton and FBLoginButtonManager

- android/src/main/java/com/facebook/reactnative/androidsdk/FBGameRequestDialogModule.java
As mentioned in [the facebook-android-sdk source code](https://github.com/facebook/facebook-android-sdk/blob/main/facebook-share/src/main/java/com/facebook/share/widget/GameRequestDialog.java#L50) ，`com.facebook.share.widget.GameRequestDialog` is deprecated should use `com.facebook.gamingservices.GameRequestDialog` instead
**Test Plan**
`GameRequestDialog.canShow` and `GameRequestDialog.show` works fine on android app.
> fix: Replace deprecated GameRequestDialog class

- android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java
Willing to fix deprecated calls in `buildAppInviteContent` mentioned in #159, but found out that `buildAppInviteContent` is no longer in use. 
Also found `buildAppGroupCreationContent` is not in use.
Remove `buildAppInviteContent` and `buildAppGroupCreationContent` from Utility.java in this PR.
**Test Plain**
Successfully build an example app for Android.
> fix(android): remove dead code

- android/build.gradle
Jcenter is down now ([Check status here](https://status.bintray.com)).
It isn't related to the [library sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) because it will be in read mode for a long time but we should replace it.
> fix: delete jcenter use to solve problem with outage and future sunset

- android/src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java
- ios/RCTFBSDK/core/RCTFBSDKAppEvents.m
- jest/mocks/index.js
- src/FBAppEventsLogger.ts
Issue occurred when called `setUserID(null)` of AppEventLogger. clearing user id is required when the user signed out.
I found that the `clearUserID` is missing; [facebook-android-sdk](https://github.com/facebook/facebook-android-sdk/blob/9c8d4be04239753a1aa20150520a5778d76aaceb/facebook-core/src/main/java/com/facebook/appevents/AppEventsLogger.kt#L502-L506), [facebook-ios-sdk](https://github.com/facebook/facebook-ios-sdk/blob/3df9d495cde87f1ce895b642524da766b3bd76aa/FBSDKCoreKit/FBSDKCoreKit/AppEvents/FBSDKAppEvents.m#L679-L682
)
I added clearUserID in this PR.
> feat: add clearUserID to AppEventsLogger (`setUserId(null)` throws exception from SDK)

- package.json
Without this file, local builds in node_modules/react-native-fbsdk-next don't work,
and then patch-package isn't as useful
> fix(build, typescript): include tsconfig.json in npm package

- src/FBAppEventsLogger.ts
This allows the module to work unmocked in a jest context
Fixes #188
> fix(test): safely dereference NativeModule for test compat

- src/FBAppEventsLogger.ts
This makes the `AppEventsLogger.getConstants` code cleaner without changing functionality. 
--
Besides, I've made a few tests, the jest will still fail with the error message
> Invariant Violation: `new NativeEventEmitter()` requires a non-null argument. 
that means the user of this package will need to add 
> jest.mock('react-native/Libraries/EventEmitter/NativeEventEmitter');
in their jest file.
But after that, if tend to call `AppEventsLogger.logEvent`  in jest will still fail at 
https://github.com/thebergamo/react-native-fbsdk-next/blob/a6c488ee85ebd91ca2b2f203f8d0cf49a937cb2b/src/FBAppEventsLogger.ts#L172
because AppEventsLogger is `undefined` after all.
The simplest way for now I think is to just mock the whole package
> jest.mock('react-native-fbsdk-next)
but in my opinion, for …
> refactor: make the `getConstants` call cleaner

- README.md
I was a bit confused when I first saw the new AEM log function - it wasn't clear if I had to use it for purchases as well as regular events, and if so, what event name to use.
So I added some more explanation. Hopefully this is helpful.
One thing that I didn't know how to do was convert the logEvent args (Array<number | Params>) into the Record<string, string | number> type needed for logAEMEvent. Any help on that would be appreciated.
> docs: include example of how to use AEM event logger

- RNFBSDKExample/ios/Podfile.lock
- react-native-fbsdk-next.podspec
Bump facebook-ios-sdk to 12.3.2, ran it locally, seems fine?
Fixes #198 
Note that v13 for both android and ios are out now but they appear to be breaking changes, so, it's good to get a version out with what will likely be the last v12 release before breaking things
> feat(ios, sdk): bump facebook-ios-sdk to 12.3.2

- RNFBSDKExample/App.js
- android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginManagerModule.java
- ios/RCTFBSDK/login/RCTFBSDKLoginManager.m
- src/FBLoginManager.ts
This pull request replicates the functionality added in facebookarchive/react-native-fbsdk#720 in order to facilitate the requesting of data access permissions when they have expired. The native Facebook SDK exposes a method on the LoginManager class (`reauthorizeDataAccess`) that the changes in this pull request exposes to the JS layer. 
Test Plan:
We've modified the example app to call the new method. We've also tested this with a separate app to verify the code is behaving as expected.
> feat: Add reauthorizeDataAccess method to LoginManager

- package.json
The expo plugin feature in #192 added a `plugin/tsconfig.json` that specifies an output dir
The main bob build is picking that up for some reason, so the types output dir we are referencing in the `types` key of `package.json` is no longer correct, we need to point it one directory in for the new `src` output directory
This works for me locally when I change it in one of my projects
I was unable to quickly reproduce the issue with a jest test to enforce this in the future unfortunately (PRs for that welcome!) so I'll wait to see if someone else on #206 can confirm it works for them
Fixes #206
> fix(types): specify new types output dir after expo plugin addition

- ios/ExpoAdapterFBSDKNext.podspec
Hi, I have a mistake in podspec. This commit will remove unnecessary compiler_flags
> fix(expo, ios): remove unnecessary compiler_flags in plugin podspec

- src/FBAppEventsLogger.ts
AppEventsLogger.clearUserID is deprecated and suggests using "setUserID(null)"
However, setUserID is currently not typed to allow null values.
Test Plan:
no test plan
> fix(types): allow null value for AppEventsLogger.setUserID

- src/FBAppEventsLogger.ts
> fix(android, setUserId): temporary android workaround for using setUserID(null)

- jest/mocks/index.js
Fix issue where `jest.spyOn(LoginManager, 'logOut')` would raise `Cannot spy the logOut property because it is not a function; undefined given instead`
> fix(jest): add LoginManager.logOut + AccessToken mocks

- README.md
- RNFBSDKExample/ios/Podfile.lock
- RNFBSDKExample/ios/RNFBSDKExample.xcodeproj/project.pbxproj
- android/build.gradle
- android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java
- ios/RCTFBSDK/share/RCTConvert+FBSDKSharingContent.m
- ios/RCTFBSDK/share/RCTFBSDKGameRequestDialog.h
- ios/RCTFBSDK/share/RCTFBSDKGameRequestDialog.m
- ios/RCTFBSDK/share/RCTFBSDKMessageDialog.m
- react-native-fbsdk-next.podspec
This is a PR for updating the library to the latest FB sdk as raised on #208 
Facebook post introducing the new version [here](https://developers.facebook.com/blog/post/2022/02/24/introducing-facebook-platform-sdk-13-related-updates/)
Please refer to the official changelog [here](https://github.com/facebook/facebook-ios-sdk/blob/main/CHANGELOG.md), main things to note are:
```
The minimum supported version of iOS is now 11.0 for all frameworks. 
The minimum supported version of tvOS is now 11.0 for all frameworks. 
The XCFramework binaries are now built with Xcode 13 so Xcode 12 is no longer supported.
```
```
Starting with the v13.0 release, client tokens must be included in apps for Graph API calls. 
An exception is now raised when running apps without a client token.
```
None
Please …
> feat(sdks): Update to v13 of native SDKs

- android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginButtonManager.java
- android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginManagerModule.java
- android/src/main/java/com/facebook/reactnative/androidsdk/FBShareDialogModule.java
- android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java
Fixes #239 
Test Plan:
I don't think it needs a test case, but I can provide one if necessary
> fix(android): ShareDialog.setMode('native') throws in Turkish language

- react-native-fbsdk-next.podspec
Should fix an archive error on iOS
See: https://github.com/facebook/facebook-ios-sdk/issues/2062#issuecomment-1117736024
Fixes #244
Test Plan:
- Should have no regressions
- @caiorrsdeg or myself can verify it archives on Xcode 13.2.1 (most recent Xcode available for macOS 11 machines)
> fix(ios): use facebook-ios-sdk 13.2.0 / archive with Xcode < 13.3

- plugin/build/withFacebookIOS.d.ts
- plugin/build/withFacebookIOS.js
- plugin/src/__tests__/withFacebookIOS-test.ts
- plugin/src/withFacebookIOS.ts
I'm in the process of migrating from `expo-facebook` to this library. Thereby I ran into the issue mentioned in #228, where the new SDK requires the facebook client token to be set in the info plist. This PR adds the client token to the expo config plugin, so that the workaround does not need to be used.
> fix(expo, ios): add client token to info plist (fixes #228)

- plugin/build/config.js
- plugin/src/__tests__/withUserTrackingPermission-test.ts
- plugin/src/config.ts
When trying to submit an update via App Store Connect, I was greeted with following issue:
The cause for this is that the expo plugin config variable `iosUserTrackingPermission` is not passed through. Thus the `withUserTrackingPermission` sub-function will always add the default user tracking permission string. This pull request fixes this.
Test Plan:
I linked this package locally and ran `expo prebuild` once with the change and once without, while checking `ios/MyProject/Info.plist` for `NSUserTrackingUsageDescription`. Without change, it is present. With change, it is gone.
--
I have also added tests for `withUserTrackingPermission`. Please let me know if you'd like to keep them. The tests would not have found the issue, since they only test the `withUserTrackingPermission` function.
It …
> fix(expo, ios): pass through config for ios user tracking permission

- jest/mocks/index.js
- package.json
- plugin/src/__tests__/withFacebookAndroid-test.ts
- plugin/src/__tests__/withFacebookIOS-test.ts
- plugin/src/__tests__/withSKAdNetworkIdentifiers-test.ts
- plugin/src/config.ts
- plugin/src/withFacebook.ts
- plugin/src/withFacebookAndroid.ts
- plugin/src/withFacebookIOS.ts
- plugin/src/withSKAdNetworkIdentifiers.ts
- src/models/FBSDKCallback.ts
This PR:
- Removes the [require pragma](https://prettier.io/docs/en/options.html#require-pragma) option from the prettier config. Only one file needed formatting, so fully transitioning to prettier here should not hurt.
- Includes the jest and plugin folders in the prettier config. Let me know what you think.
> refactor(formatting): expand prettier scope to include jest and plugin files

- README.md
- plugin/build/config.d.ts
- plugin/build/withFacebookIOS.js
- plugin/src/__tests__/withUserTrackingPermission-test.ts
- plugin/src/config.ts
- plugin/src/withFacebookIOS.ts
Fixes #272
Test Plan: `yarn test`
Please give any feedback whether it is better to have default `NSUserTrackingUsageDescription` or make it optional.
> fix(expo, ios)!: iosUserTrackingPermission no longer added by default in Expo

- react-native-fbsdk-next.podspec
Facebook is asking for the sdk to be updated. This ups the fb-sdk for ios to 14.1.0.
Fixes #294
> feat(ios, sdk): bump facebook-ios-sdk to 14.1.0

- README.md
Just adding some info that seems like it was unclear (lot of people asking for it in Expo Discord)
> docs: Clarify info for people migrating from `expo-facebook` to `react-native-fbsdk-next`

- README.md
I corrected the configuration of FBAEMReporter for iOS as it needs a reporter parameter.
> docs(ios, AEM): AEM setup requires a reporter parameter in API call

- README.md
- RNFBSDKExample/ios/Podfile.lock
- RNFBSDKExample/ios/RNFBSDKExample/AppDelegate.mm
- refresh-example.sh
it has moved as part of their swift conversion, example did not have linking so did not detect it
Test Plan:
A bunch of compilation tests, need to update v15 release notes as well
Fixes #317
> docs(ios): facebook-ios-sdk needs FBSDKCoreKit/FBSDKCoreKit-swift.h import

- package.json
- yarn.lock
This will bring make this library more compatible with the latest expo SDK release
Fixes #309
Test Plan:
`yarn test`
Thanks for the awesome library!
> fix(expo): bump expo dependency

- README.md
The `scheme` option is also not listed and is required for proper operation, e.g. on iOS with Facebook app installed.
Docs-only change.
> Update README to better clarify config plugin options

- ios/ExpoAdapterFBSDKNext.podspec
Bumping expo adapter version for a minimum iOS version of 13.0 for supporting expo sdk 47 
Fixes #346
> feat(Expo): bump Expo Adapters version from 12.0 to 13.0

- README.md
- android/src/main/java/com/facebook/reactnative/androidsdk/FBSettingsModule.java
- ios/RCTFBSDK/core/RCTFBSDKSettings.m
- src/FBSettings.ts
- src/util/validate.ts
The [expo-facebook](https://github.com/expo/expo-facebook) module was deprecated in Expo SDK 45 and removed in Expo SDK 46. This PR aims to provide developers migrating from `expo-facebook` to `react-native-fbsdk-next` with some documentation to ease the transition.
Also adds support for the following Facebook SDK methods:
* **setAppName**
* **setGraphAPIVersion**
* **setAutoLogAppEventsEnabled**
* **setAdvertiserIDCollectionEnabled**
Fixes #142 
Update the App.js
```js
Settings.setAppID("<your-app-id>");
Settings.setAppName("<your-app-name>");
Settings.setGraphAPIVersion("<graph-api-version>"); // e.g. "v14.0"
Settings.setAutoLogAppEventsEnabled(true);
Settings.initializeSDK()
```
All changes were verified by running the `yarn example:android` & `yarn example:ios` scripts.
> docs: Add expo facebook migration guide

- package.json
- yarn.lock
Expo doctor (`npx expo-doctor`) warns about this package using an outdated version of expo config plugins. This PR aligns the dependencies used by this packages config plugin with [the latest expo recommendations](https://docs.expo.dev/home/config-plugins/development-and-debugging/). They now recommend having expo as an optional peer dependency. It also says:
> For simple config plugins that depend on core, stable APIs, such as a plugin that only modifies AndroidManifest.xml or Info.plist, you can use a loose dependency [...]
I verified that's the case.
Fixes #404
(only putting that here so said issue gets automatically closed).
Test Plan:
I ran the unit tests for the config plugin (`yarn test`) which verify the modifications made by the plugin.
> fix(expo): Update expo config plugin dependencies

- README.md
Update readme for iosUserTrackingPermission config. This optionnal value can be a string or false.
> fix(readme): iosUserTrackingPermission: string | false

- android/src/main/java/com/facebook/reactnative/androidsdk/FBSettingsModule.java
- ios/RCTFBSDK/core/RCTFBSDKSettings.m
- src/FBSettings.ts
setClientToken is available on the Facebook SDK: 
- iOS: https://developers.facebook.com/docs/reference/ios/current/constants/FBSDKSettings
- Android: https://developers.facebook.com/docs/reference/android/current/class/FacebookSdk
Adding functions to handle setClientToken inapp
> feat: add setClientToken method

- README.md
- RNFBSDKExample/ios/Podfile.lock
- RNFBSDKExample/ios/RNFBSDKExample/AppDelegate.mm
- android/build.gradle
- ios/RCTFBSDK/core/RCTFBSDKAEMReporter.m
- react-native-fbsdk-next.podspec
- refresh-example.sh
Updated Facebook SDK to 16.1.3 which is the current latest
Have tested with building the example app locally and ensuring all tests pass.
Based on PR #417
> feat(sdks): Upgrade FBSDK to 16.1.3

- src/FBAppEventsLogger.ts
Adding type to AppEvents and AppEventsParams to be able to see what types are available to be used following AppEventsLogger.AppEvents, making it easier when creating a log.
> feat(EventLogger): add type for AppEvents and AppEventsParams

- README.md
- RNFBSDKExample/ios/RNFBSDKExample/AppDelegate.mm
- refresh-example.sh
This fix the issue for case-sensitive file systems. 
It would have no impact for not case-sensitive user systems.
Build error:
> docs(ios): fix 'FBSDKCoreKit/FBSDKCoreKit-swift.h' file not found on case-sensitive filesystems

- android/src/main/java/com/facebook/reactnative/androidsdk/FBAccessTokenModule.java
If initialize was called correctly, accessTokenTracker would always be non-null
But just in case the state is not correctly initialized, we can avoid crashing
* Fixes #473 
Test Plan:
Untested. A null-check should be harmless though. @GreenFella will test the new release and report success/failure
> fix(android): avoid crash on react-native reload if not initialized

- android/build.gradle
- android/src/main/AndroidManifest.xml
Test Plan:
https://github.com/react-native-community/discussions-and-proposals/issues/671
React Native 0.73 will depend on Android Gradle Plugin (AGP) 8.x. This will require all the libraries to specify a namespace in their build.gradle file. We added a compatibility layer for libraries that haven't specified a namespace, but please consider updating your libraries nonetheless.
> feat(android): RN-0.73 and Android Gradle Plugin 8.0 Compatibility Fix

- plugin/build/withFacebookAndroid.js
- plugin/src/__tests__/withFacebookAndroid-test.ts
- plugin/src/withFacebookAndroid.ts
This takes the contents of #504 and just does two things in order to get it done before I turn my attention elsewhere:
- rebases to master/head so CI will work
- runs and commits result of `yarn validate:prettier:fix` so CI will pass
Other than that all code is from @andrejpavlovic
Supercedes / Closes #504 
Fixes #329
> fix(expo): update scheme injection

- android/src/main/java/com/facebook/reactnative/androidsdk/FBSettingsModule.java
- android/src/main/java/com/facebook/reactnative/androidsdk/RCTLoginButton.java
- android/src/main/java/com/facebook/reactnative/androidsdk/RCTLoginButtonEvent.java
- ios/RCTFBSDK/login/RCTFBSDKLoginButtonManager.h
- ios/RCTFBSDK/login/RCTFBSDKLoginButtonManager.m
- ios/RCTFBSDK/login/RCTFBSDKLoginButtonView.h
- ios/RCTFBSDK/login/RCTFBSDKLoginButtonView.m
This PR adds Android and iOS support for the new architecture relying on the compatibility layer. 
two main changes were required for this to work:
1. Remove `static` from all functions annotated with `@ReactMethod` given that in bridgeless it would throw the following error 
2. Use the event dispatcher to send events from the native side to JS and adding a RCTLoginButtonEvent class
Had to create a dedicated class for the RCTFBSDKLoginButton view in order to export the `onChange` view property of type  `RCTBubblingEventBlock` and declare this property on the UIView wrapping the button (`FBSDKLoginButton` is a final class and can't be extended)
Locally run `refresh-example` to update to the latest RC and tested Android and iOS on the old and new architectures …
> feat: add support for new architecture in compatibility mode

- RNFBSDKExample/ios/Podfile.lock
- react-native-fbsdk-next.podspec
simple bump to 17.3.0 for iOS SDK
note that 17.2.0 was never released for some reason
seems to compile and work fine locally
> fix(ios, sdk): adopt facebook-ios-sdk 17.3.0

- package.json
- Fixes #561 
I believe v18+ will work for everyone as long as our CI is 20+ as required by our semantic release infrastructure
CI will be the test - if it passes, then the PR is good in general
*then* if a release works, it is 100% good, but no way to tell that until post-merge so I'll watch it as release happens
> fix: loosen engine semver to be node 18+ not 20+

- RNFBSDKExample/ios/RNFBSDKExample/Info.plist
- refresh-example.sh
> fix(example app): use boolean values for `FacebookAutoLogAppEventsEnabled` and `FacebookAdvertiserIDCollectionEnabled`

- ios/RCTFBSDK/core/RCTFBSDKProfile.m
- src/FBProfile.ts
Since Graph API cannot be used, this seems to be the only way to access additional user profile fields such as user's birthday, as per [official documentation](https://developers.facebook.com/docs/facebook-login/limited-login/ios/).
Fixes #525
Test Plan:
I granted all personalisation permissions to my app via the developer portal and specified them during login.
However, not all fields returned were populated even though the permission was granted.
So I created a test profile for e2e testing to ensure all mappings are working.
> feat(ios): make all permitted user profile fields available when using limited login

- README.md
After searching endlessly why the login was deferring to `limited` in iOS devices, I finally stumbled upon [an answer in an issue](https://github.com/thebergamo/react-native-fbsdk-next/issues/520#issuecomment-2067687075) in this repo which states the exact solution for the problem.
> docs: add documentation for troubleshooting limited login view in iOS.

- README.md
**ISSUE**
My app has multiple SSO options set up. When I added Facebook SSO using this package, it worked fine for Android and some iOS devices as well. But for some iOS devices, the app navigates to the Facebook app to authenticate and switches back to my app with a deep link like `fbAppId://somePermissions%data%etc`.
After debugging for an entire day, I realized that I had put `RCTLinkinganager` condition before `FBSDKApplicationDelegate` and just changing the order fixed it.
I believe this short note would be helpful for anyone having multiple other SSOs while integrating this package
> docs: Deeplink ordering note added to README.md

- RNFBSDKExample/ios/Podfile.lock
- android/build.gradle
- react-native-fbsdk-next.podspec
This pull request updates the Android Facebook SDK to version 18. 
- Reason: SDK v18 introduces better support for Google Play Billing Library v5 - v7
- Tested: Verified on both Android and iOS using the example app.
- No breaking changes observed.
> feat(android): adopt facebook-android-sdk v18.0.0

- android/src/main/AndroidManifest.xml
Facebook SDK 18 introduced [Google Privacy Sandbox adservices API](https://github.com/facebook/facebook-android-sdk/commit/142b47a8beaa2ca23ac049ac8b96e837399457c2), and when this SDK was updated to 18, that change was pulled in here in https://github.com/thebergamo/react-native-fbsdk-next/pull/595. This means that if a user has a package that tries to declare the same resource either A) The user has to do this override in their AndroidManifest or B) We do it here like how [react-native-google-mobile-ads](https://github.com/invertase/react-native-google-mobile-ads/pull/660) does it
- Fixes #596
- Fixes #597 
Test Plan:
1. I made the changes locally on my own project in Android Studio and made sure that it compiled successfully:
2. I made the change to the source code, changed the fork's …
> fix: add replace for the new AD_SERVICES_CONFIG introduced in V18
